name: ci

on:
  push:
    branches:
      - '**'

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-go@v1
      with:
        go-version: '1.12'

    - name: test and build
      run: make